name: ceoplayground
favicon: null
layout_spectrum: 0.3729092846624553
typography_spectrum: 0.5383997762110084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6489459522999823
  lightness: 0.8436033467296511
  saturation: 0.4408598458394408
  rhythmicContrast: 0.415426641702652
purpose: []
